### ISSUE TITLE
Do you have a single solution for all projects?

### ISSUE THREAD

**Issue by derodevil** [syncfusion/winforms-demos#1]
I really find it hard to run them with separated nuget packages where I have to restore one by one, one project one package. It is also hard to run and switch between projects because you don't put it in single solution where I have to select folder inside a folder and inside a folder and inside a folder, puffh.. Try to learn from other company.  Why don't you just include the .exe files where we can easily run and check how syncfusion really look like? This samples are really annoying

**Comment by abooarulraj** [comment]
> I really find it hard to run them with separated nuget packages where I have to restore one by one, one project one package. It is also hard to run and switch between projects because you don't put it in single solution where I have to select folder inside a folder and inside a folder and inside a folder, puffh.. Try to learn from other company. Why don't you just include the .exe files where we can easily run and check how syncfusion really look like? This samples are really annoying

@derodevil We regret for the inconvenience caused for you and we thank you for your valuable feedback. We already have plans to improve the samples usability and it will be done in near future. As of now, we suggest you install our setup and run the sample browser to view the samples intuitively.
Download link: https://www.syncfusion.com/forums/140650/essential-studio-2018-volume-3-service-pack-release-v16-3-0-29-available-for-download
